/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppLanggananRouteImport } from './routes/_app/langganan'
import { Route as AppKantongRouteImport } from './routes/_app/kantong'
import { Route as AppGoalsRouteImport } from './routes/_app/goals'
import { Route as AppCatatanKeuanganRouteImport } from './routes/_app/catatan-keuangan'
import { Route as ApiCronLanggananPushRemindersRouteImport } from './routes/api/cron/langganan-push-reminders'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthAuthLoginRouteImport } from './routes/_auth/auth.login'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLanggananRoute = AppLanggananRouteImport.update({
  id: '/langganan',
  path: '/langganan',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppKantongRoute = AppKantongRouteImport.update({
  id: '/kantong',
  path: '/kantong',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCatatanKeuanganRoute = AppCatatanKeuanganRouteImport.update({
  id: '/catatan-keuangan',
  path: '/catatan-keuangan',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiCronLanggananPushRemindersRoute =
  ApiCronLanggananPushRemindersRouteImport.update({
    id: '/api/cron/langganan-push-reminders',
    path: '/api/cron/langganan-push-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthLoginRoute = AuthAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/catatan-keuangan': typeof AppCatatanKeuanganRoute
  '/goals': typeof AppGoalsRoute
  '/kantong': typeof AppKantongRoute
  '/langganan': typeof AppLanggananRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/login': typeof AuthAuthLoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/langganan-push-reminders': typeof ApiCronLanggananPushRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/catatan-keuangan': typeof AppCatatanKeuanganRoute
  '/goals': typeof AppGoalsRoute
  '/kantong': typeof AppKantongRoute
  '/langganan': typeof AppLanggananRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/login': typeof AuthAuthLoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/langganan-push-reminders': typeof ApiCronLanggananPushRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_app/catatan-keuangan': typeof AppCatatanKeuanganRoute
  '/_app/goals': typeof AppGoalsRoute
  '/_app/kantong': typeof AppKantongRoute
  '/_app/langganan': typeof AppLanggananRoute
  '/api/chat': typeof ApiChatRoute
  '/_app/': typeof AppIndexRoute
  '/_auth/auth/login': typeof AuthAuthLoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/langganan-push-reminders': typeof ApiCronLanggananPushRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catatan-keuangan'
    | '/goals'
    | '/kantong'
    | '/langganan'
    | '/api/chat'
    | '/auth/login'
    | '/api/auth/$'
    | '/api/cron/langganan-push-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catatan-keuangan'
    | '/goals'
    | '/kantong'
    | '/langganan'
    | '/api/chat'
    | '/auth/login'
    | '/api/auth/$'
    | '/api/cron/langganan-push-reminders'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/catatan-keuangan'
    | '/_app/goals'
    | '/_app/kantong'
    | '/_app/langganan'
    | '/api/chat'
    | '/_app/'
    | '/_auth/auth/login'
    | '/api/auth/$'
    | '/api/cron/langganan-push-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronLanggananPushRemindersRoute: typeof ApiCronLanggananPushRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/langganan': {
      id: '/_app/langganan'
      path: '/langganan'
      fullPath: '/langganan'
      preLoaderRoute: typeof AppLanggananRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/kantong': {
      id: '/_app/kantong'
      path: '/kantong'
      fullPath: '/kantong'
      preLoaderRoute: typeof AppKantongRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/goals': {
      id: '/_app/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/catatan-keuangan': {
      id: '/_app/catatan-keuangan'
      path: '/catatan-keuangan'
      fullPath: '/catatan-keuangan'
      preLoaderRoute: typeof AppCatatanKeuanganRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/cron/langganan-push-reminders': {
      id: '/api/cron/langganan-push-reminders'
      path: '/api/cron/langganan-push-reminders'
      fullPath: '/api/cron/langganan-push-reminders'
      preLoaderRoute: typeof ApiCronLanggananPushRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/auth/login': {
      id: '/_auth/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthAuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppCatatanKeuanganRoute: typeof AppCatatanKeuanganRoute
  AppGoalsRoute: typeof AppGoalsRoute
  AppKantongRoute: typeof AppKantongRoute
  AppLanggananRoute: typeof AppLanggananRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppCatatanKeuanganRoute: AppCatatanKeuanganRoute,
  AppGoalsRoute: AppGoalsRoute,
  AppKantongRoute: AppKantongRoute,
  AppLanggananRoute: AppLanggananRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthAuthLoginRoute: typeof AuthAuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAuthLoginRoute: AuthAuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronLanggananPushRemindersRoute: ApiCronLanggananPushRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
